ʔbu̯ɩ̈n [บน ‘above’]
ʔblɩ̈en [เดือน ‘moon, month’]
drɩ̈o [เรือ ‘boat’]
ɣɩ̈ən [คืน ‘night’]
ňuŋ [ยุง ‘mosquito’]
siuᴮ [สิ่ว ‘chisel’]
bɔᴮ [พ่อ ‘father’]
rueᴮ [รั่ว ‘leak’]
haᶜ [ห้า ‘five’]
rɔiᶜ [ร้อย ‘string’]
ʔi̯et [เอ็ด ‘one’]
pruɔk [ตอก ‘bamboo strip’]
dlək [ลัก ‘steal’]
muək [มูก ‘mucus’]
